lab3/vintoniak_project/app/portfolio/__init__.py
from flask import Blueprint

portfolio = Blueprint("portfolio", __name__, template_folder="templates/portfolio")

lab3/vintoniak_project/app/portfolio/views.py
import os
from flask import render_template, redirect, url_for, request, abort
from datetime import datetime
from .data import certificats
from . import portfolio

mySkills = [
    {
        "skillName": "HTML",
        "level": "skillful",
        "icon": "devicon-html5-plain colored fs-45"
    },
    {
        "skillName": "CSS",
        "level": "skillful",
        "icon": "devicon-css3-plain colored fs-45"
    },
    {
        "skillName": "Python",
        "level": "skillful",
        "icon": "devicon-python-plain colored fs-45"
    },
    {
        "skillName": "GIT",
        "level": "beginer",
        "icon": "devicon-github-original colored fs-45"
    },
    {
        "skillName": "SQL",
        "level": "skillful",
        "icon": "fa fa-database fs-45 text-info"
    }
] 


@portfolio.route('/')
def home():
    osInfo = os.environ.get('OS')
    agent = request.user_agent
    time = datetime.now().strftime("%H:%M:%S")
    
    return render_template('home.html', certificats=certificats, agent=agent, time=time, osInfo=osInfo)

@portfolio.route('/skills/<int:id>')
@portfolio.route('/skills')
def skills(id=None):
    
    if id:
        if id > len(mySkills):
            abort(404)
        else:
            index = id - 1
            skill = mySkills[index]
            return render_template('skill.html', skill=skill, id=id)    
    else:
        return render_template('skills.html', mySkills=mySkills)
    
    
@portfolio.route('/certificates')
def certificates():
    osInfo = os.environ.get('OS')
    agent = request.user_agent
    time = datetime.now().strftime("%H:%M:%S")
    
    return render_template('certificates.html', certificats=certificats)

lab3/vintoniak_project/app/portfolio/templates/portfolio/certificates.html
{% extends 'base.html' %}
{% block title %}Certificates{% endblock %}
{% block content %}
<div class="container mt-50">
    <h1 class="text-center text-primary">My certificates</h1>
    <br><br>
    {% for item in certificats %}
        <h3>{{ item["name"] }}</h3><br>
        <!--<img src="../static/images/{{item['photoName']}}" alt="certificat" class="certificates"><br><br>-->

        <img src="{{ url_for('static', filename='/'.join(['images', item['photoName']])) }}" alt="certificat" class="certificates"/><br><br>
        <hr><br>
    {% endfor %}
</div>
{% endblock %}

lab3/vintoniak_project/app/portfolio/templates/portfolio/home.html
{% extends 'base.html' %}
{% block title %}Portfolio{% endblock %}
{% block content %}

    <!-- Photo, Name, Descr -->
    <div class="container mt-30">
        <div class="row justify-content-center">
            <div class="col-3">
                <img src="{{ url_for('static', filename='images/MyPhoto2.png' ) }}" alt="MyPhoto" class="myPhoto">
            </div>
            <div class="col-4">
                <h1 class="big-title">Roman Vintoniak</h1>
                <hr>
                <p>
                    I'm 20. I communicate freely and study a lot, and I am a process person.
                    I like to develop Web applications. It is important for me to work in a team.
                </p>
            </div>
        </div>
    </div>

    <!-- Contacts -->
    <div class="strip bg-dark mt-50">
        <div class="container">
            <div class="row justify-content-center text-center">
                <div class="col-3">
                    <i class="bi bi-envelope-fill text-primary"></i> romanvintoniak03@gmail.com
                </div>
                <div class="col-3">
                    <i class="bi bi-telephone-fill text-primary"></i> +380631998947
                </div>
                <div class="col-3">
                    <i class="bi bi-telegram text-primary"></i> Roman Vintoniak
                </div>
                <div class="col-3">
                    <i class="bi bi-geo-alt-fill text-primary"></i> Ivano-Frankivsk, Ukraine
                </div>
            </div>
        </div>
    </div>

    <!-- EDUCATION | WORK EXPERIENCE | LANGUAGES -->
    <div class="container mt-80">
        <div class="row justify-content-center">
            <div class="col-4">
                <div class="card border-dark mb-3" style="max-width: 20rem;">
                    <div class="card-body">
                      <h4 class="card-title">EDUCATION</h4>
                      <hr>
                      <p class="card-text">Vasyl Stefanyk Precarpathian National University.</p>
                      <p class="card-text text-body-tertiary">2021-present</p>
                    </div>
                </div>
            </div>    
            <div class="col-4">
                <div class="card border-dark mb-3" style="max-width: 20rem;">
                    <div class="card-body">
                      <h4 class="card-title">WORK EXPERIENCE</h4>
                      <hr>
                      <p class="card-text">None :(</p>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="card border-dark mb-3" style="max-width: 20rem;">
                    <div class="card-body">
                      <h4 class="card-title">LANGUAGES</h4>
                      <hr>
                      <ul>
                        <li><p class="card-text">Ukrainian - Native Speaker</p></li>
                        <li><p class="card-text">English - B1</p></li>
                      </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Projects -->
    <div class="container mt-80">
        <h2>Personal projects</h2>
        <p>
            - Advertising Manager (in progres) -> 
            <a href="https://github.com/RomanVintoniak/Advertising-manager">git</a>
        </p>
        <p>- Telegram Bot Project</p>
        <p>- Web Site for the local Hotel</p>
    </div>

    <!-- Certificats -->
    <div class="container mt-80">
        <h2 class="text-center">
            <a href="{{ url_for('portfolio.certificates') }}">Сertificates</a>
        </h2>
        <table class="table table-hover mt-30">
            <thead>
              <tr>
                <th scope="col">№</th>
                <th scope="col">Name</th>
                <th scope="col">Platform</th>
                <th scope="col">Instractor name</th>
                <th scope="col">Date</th>
              </tr>
            </thead>
            <tbody>
                {% for item in certificats %}
                    <tr class="table-dark">
                        <th scope="row">{{ loop.index }}</th>
                        <td>{{ item["name"] }}</td>
                        <td>{{ item["platform"] }}</td>
                        <td>{{ item["instractorName"] }}</td>
                        <td>{{ item["date"] }}</td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>

    <!-- Interests -->
    <div class="container mt-80">
        <h2>Interests</h2>
        <br>
        <span class="border-primary">
            My hobbies playing computer games and I like to travel to
            the mountains and hiking
        </span><br><br>
        <span class="border-primary">
            When I have free time I like to play on piano or guitar
        </span><br><br>
        <span class="border-primary">
            Professional development
        </span>
    </div>
    
    {% include 'footer.html' %}
{% endblock %}

lab3/vintoniak_project/app/portfolio/templates/portfolio/skill.html
{% extends 'base.html' %}
{% block title %}Skill {{ skill['skillName'] }}{% endblock %}
{% block content %}
    <h1 class="text-center mt-80">
        {{ id }}. {{ skill['skillName'] }}
    </h1>

    <br><br><br><br><br><br><br><br>
{% endblock %}

lab3/vintoniak_project/app/portfolio/templates/portfolio/skills.html
{% extends 'base.html' %}
{% block title %}Skills{% endblock %}
{% block content %}
    <h1 class="text-center big-title mt-30">My skills</h1>

    <div class="container mt-50">
        {% for skill in mySkills %}
            <h3>
                <i class="{{ skill['icon'] }}"></i> 
                <a href="{{ url_for('portfolio.skills', id=loop.index) }}">{{ skill["skillName"] }}</a>&nbsp;&nbsp; — &nbsp;&nbsp;{{ skill["level"] }}
            </h3>
            <br>
        {% endfor %}
        <br>
        <h3>Total number of skills: {{ mySkills.__len__() }}</h3>
    </div>
{% endblock %}